language: groovy

jdk:
  - openjdk7

env:
- TERM=dumb

before_install: chmod +x ./application/gradlew

script: ./application/gradlew clean build

after_success: ./application/gradlew jacocoTestReport
