language: groovy

jdk:
  - openjdk7

env:
- TERM=dumb

before_install: cd application && chmod +x ./gradlew

script: cd application && ./gradlew clean build

after_success: cd application && ./gradlew jacocoTestReport
