language: groovy

jdk:
  - openjdk7

env:
- TERM=dumb

cache:
  directories:
  - $HOME/.gradle/caches/modules-2/files-2.1
  - $HOME/.gradle/wrapper/dists

before_install:
- cd application
- chmod +x gradlew

script:
- ./gradlew build