<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Classes" nsURI="http:///Classes.ecore" nsPrefix="Classes">
  <eSubpackages name="PersonRegistry" nsURI="http:///Classes/PersonRegistry.ecore"
      nsPrefix="Classes.PersonRegistry">
    <eClassifiers xsi:type="ecore:EClass" name="PersonRegistry"/>
    <eClassifiers xsi:type="ecore:EClass" name="PersonRegistry_CreditCardInfo" eSuperTypes="#//PersonRegistry/ICreditCardInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccv" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardHolder" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICreditCardInfo" abstract="true" interface="true">
      <eOperations name="getCCV" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getCardHolder" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonRegistry_Person" eSuperTypes="#//PersonRegistry/IPerson">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="registerDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="creditCardInfo" ordered="false"
          eType="#//PersonRegistry/PersonRegistry_CreditCardInfo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="personalDiscount" ordered="false"
          upperBound="-1" eType="#//PersonRegistry/PersonRegistry_PersonalDiscount"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonRegistry_PersonalDiscount" eSuperTypes="#//PersonRegistry/IPersonalDiscount">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPersonalDiscount" abstract="true"
        interface="true">
      <eOperations name="hasExpired" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getValue" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="getLabel" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getExpirationDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPerson" abstract="true" interface="true">
      <eOperations name="getBirthDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eOperations name="getFirstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getLastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getSSN" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getRegisterDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eOperations name="setBirthDate" ordered="false" lowerBound="1"/>
      <eOperations name="setFirstName" ordered="false" lowerBound="1"/>
      <eOperations name="setLastName" ordered="false" lowerBound="1"/>
      <eOperations name="setSSN" ordered="false" lowerBound="1"/>
      <eOperations name="setRegi" ordered="false" lowerBound="1"/>
      <eOperations name="getDiscounts" ordered="false" upperBound="-1" eType="#//PersonRegistry/IPersonalDiscount"/>
      <eOperations name="getCreditCard" ordered="false" eType="#//PersonRegistry/ICreditCardInfo"/>
      <eOperations name="createCreditCardInfo" ordered="false" lowerBound="1"/>
      <eOperations name="removeCreditCard" ordered="false" lowerBound="1"/>
      <eOperations name="createCreditCard" ordered="false" lowerBound="1">
        <eParameters name="number" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="month" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="year" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="cardHolder" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeDiscount" ordered="false" lowerBound="1">
        <eParameters name="label" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="addDiscount" ordered="false" lowerBound="1">
        <eParameters name="label" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="value" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eParameters name="expirationDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="getId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonRegistry_Blacklist">
      <eOperations name="isBlacklisted" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="person" ordered="false" lowerBound="1" eType="#//PersonRegistry/PersonRegistry_Person"/>
      </eOperations>
      <eOperations name="add" ordered="false" lowerBound="1">
        <eParameters name="person" ordered="false" lowerBound="1" eType="#//PersonRegistry/PersonRegistry_Person"/>
      </eOperations>
      <eOperations name="remove" ordered="false" lowerBound="1">
        <eParameters name="person" ordered="false" lowerBound="1" eType="#//PersonRegistry/PersonRegistry_Person"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="person" ordered="false"
          upperBound="-1" eType="#//PersonRegistry/PersonRegistry_Person"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonRegistry_PersonRegistryImpl"
        eSuperTypes="#//PersonRegistry/IPersonRegistry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="person" ordered="false"
          upperBound="-1" eType="#//PersonRegistry/PersonRegistry_Person"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="blacklist" ordered="false"
          lowerBound="1" eType="#//PersonRegistry/PersonRegistry_Blacklist"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPersonRegistry" abstract="true" interface="true">
      <eOperations name="isBlacklisted" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="person" ordered="false" lowerBound="1" eType="#//PersonRegistry/IPerson"/>
      </eOperations>
      <eOperations name="createPerson" ordered="false" lowerBound="1">
        <eParameters name="birthDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getPersons" ordered="false" upperBound="-1" eType="#//PersonRegistry/IPerson"/>
      <eOperations name="addToBlacklist" ordered="false" lowerBound="1">
        <eParameters name="person" ordered="false" lowerBound="1" eType="#//PersonRegistry/IPerson"/>
      </eOperations>
      <eOperations name="removeFromBlacklist" ordered="false" lowerBound="1">
        <eParameters name="person" ordered="false" lowerBound="1" eType="#//PersonRegistry/IPerson"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Hotel" nsURI="http:///Classes/Hotel.ecore" nsPrefix="Classes.Hotel">
    <eClassifiers xsi:type="ecore:EClass" name="Hotel"/>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Room">
      <eOperations name="getProperty" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
        <eParameters name="key" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getPropertyKeys" ordered="false" lowerBound="1"/>
      <eOperations name="getPrice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="addDiscount" ordered="false" lowerBound="1">
        <eParameters name="discount" ordered="false" lowerBound="1" eType="#//Hotel/Hotel_Discount"/>
      </eOperations>
      <eOperations name="removeDiscount" ordered="false" lowerBound="1">
        <eParameters name="discount" ordered="false" lowerBound="1" eType="#//Hotel/Hotel_Discount"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePrice" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOutOfOrder" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pricingRule" ordered="false"
          lowerBound="1" eType="#//Hotel/Hotel_PricingRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomProperty" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_RoomProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomType" ordered="false"
          lowerBound="1" eType="#//Hotel/Hotel_RoomType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="discount" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Discount"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_PricingRule">
      <eOperations name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="basePrice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_RoomProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_RoomType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Discount">
      <eOperations name="hasExpired" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Occupancy">
      <eOperations name="addKeys" ordered="false" lowerBound="1">
        <eParameters name="number" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="removeKeys" ordered="false" lowerBound="1">
        <eParameters name="number" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbrOfKeys" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false"
          lowerBound="1" eType="#//Hotel/Hotel_Room"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Stay">
      <eOperations name="addService" ordered="false" lowerBound="1">
        <eParameters name="service" ordered="false" lowerBound="1" eType="#//Hotel/Hotel_Service"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkInTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOutTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="occupancy" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Hotel/Hotel_Occupancy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Service"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Service" eSuperTypes="#//Hotel/IService">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IService" abstract="true" interface="true">
      <eOperations name="getPrice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="getLabel" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Booking" eSuperTypes="#//Hotel/IBooking">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkInDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOutDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stay" ordered="false"
          lowerBound="1" eType="#//Hotel/Hotel_Stay"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="discount" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Discount"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guests" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contact" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IBooking" abstract="true" interface="true">
      <eOperations name="getContact" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getPrice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="getGuests" ordered="false" lowerBound="1" upperBound="-1"
          eType="ecore:EDataType types.ecore#//String"/>
      <eOperations name="getServices" ordered="false" upperBound="-1" eType="#//Hotel/IService"/>
      <eOperations name="getCheckInDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eOperations name="getCheckOutDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_Order" eSuperTypes="#//Hotel/IOrder">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="customer" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="booking" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Booking"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IOrder" abstract="true" interface="true">
      <eOperations name="getBookings" ordered="false" lowerBound="1" upperBound="-1"
          eType="#//Hotel/IBooking"/>
      <eOperations name="getCustomer" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_BookingSuggestion" eSuperTypes="#//Hotel/IBookingSuggestion">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false"
          lowerBound="1" eType="#//Hotel/Hotel_Room"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IBookingSuggestion" abstract="true"
        interface="true">
      <eOperations name="getPrice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="getProperties" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      <eOperations name="getStartTime" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eOperations name="getEndTime" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_SearchResult" eSuperTypes="#//Hotel/ISearchResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bookingSuggestion" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Hotel/Hotel_BookingSuggestion"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="relevance" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISearchResult" abstract="true" interface="true">
      <eOperations name="getBookingSuggestions" ordered="false" lowerBound="1" eType="#//Hotel/IBookingSuggestion"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_SearchQuery">
      <eStructuralFeatures xsi:type="ecore:EReference" name="searchParam" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_SearchParam"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="searchResult" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_SearchResult"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="occupancy" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Occupancy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Room"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_SearchParam">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_SearchImpl" eSuperTypes="#//Hotel/ISearch">
      <eStructuralFeatures xsi:type="ecore:EReference" name="searchQuery" ordered="false"
          lowerBound="1" eType="#//Hotel/Hotel_SearchQuery"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISearch" abstract="true" interface="true">
      <eOperations name="search" ordered="false" lowerBound="1" eType="#//Hotel/ISearchResult">
        <eParameters name="searchParam" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hotel_HotelImpl" eSuperTypes="#//Hotel/IHotel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="booking" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Booking"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="order" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Order"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false"
          upperBound="-1" eType="#//Hotel/Hotel_Service"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="personRegistry" ordered="false"
          lowerBound="1" eType="#//PersonRegistry/IPersonRegistry"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IHotel" abstract="true" interface="true">
      <eOperations name="checkIn" ordered="false" lowerBound="1">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="#//Hotel/IBooking"/>
        <eParameters name="numKeys" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getInvoice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="#//Hotel/IBooking"/>
      </eOperations>
      <eOperations name="getBookings" ordered="false" lowerBound="1" eType="#//Hotel/IBooking"/>
      <eOperations name="pay" ordered="false" lowerBound="1">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="#//Hotel/IBooking"/>
      </eOperations>
      <eOperations name="checkOut" ordered="false" lowerBound="1">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="#//Hotel/IBooking"/>
        <eParameters name="numKeys" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getServices" ordered="false" upperBound="-1" eType="#//Hotel/IService"/>
      <eOperations name="getOrders" ordered="false" upperBound="-1" eType="#//Hotel/IOrder"/>
      <eOperations name="placeOrder" ordered="false" lowerBound="1">
        <eParameters name="bookings" ordered="false" lowerBound="1" upperBound="-1"
            eType="#//Hotel/IBookingSuggestion"/>
        <eParameters name="guests" ordered="false" lowerBound="1" upperBound="-1"
            eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="contact" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customer" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
